### ISSUE TITLE
Is it possible to add Letterboxd as one of the options for a search?

### ISSUE THREAD

**Issue by nikivdev** [tmcknight/Movies-Alfred-Workflow#1]
I think it would really be great. Here is the website I am referring to (http://letterboxd.com). I found it a lot better than IMDB so would really love to perhaps have that as an option in the workflow.

Thank you and I hope you consider adding it.

**Comment by tmcknight** [comment]
Cool site! Looks like they don't have an API ([yet](http://letterboxd.com/api-coming-soon/)). If you see that they open up their API in the future, feel free to comment on this issue. Thanks.

**Comment by ghost** [comment]
I'd love to have the functionality to define own links for search results where I would supply a name and URL with a {imdb_id} placeholder somewhere, maybe even an icon, and then get those links in the search results as well. I guess I can easily hack that into the plugin myself, but a generic solution would really make this stand out. Any idea how tricky that would be to implement?

**Comment by vitorgalvao** [comment]
@matrixagent That is not possible. Every website and API and is different; if you want to support more websites, you need to do the legwork. There’s no way you can build a generic service where you just say “hey, add from here” and it’ll just know what to do.

**Comment by ghost** [comment]
Well… a fully generic service is not what I suggest, just one for services that support "searching" by IMDb ID via url, which is most relevant services I know. All I was asking was for the list of links _after_ a movie has been chosen to be extendible by very simple direct links. Once you know the movie, you also know the IMDb ID – as is obvious from the possibility of displaying a link to the IMDb page of that movie. I use trakt.tv more than IMDb, so I'd love to have a link to https://trakt.tv/search/imdb?query=tt4649466 in addition to the existing link to http://www.imdb.com/title/tt4649466/ – and as most services will be able to handle IMDb IDs in their search, I think it would make sense to allow configuration of a list of custom URLs where a placeholder of the IMDb ID is replaced.

**Comment by vitorgalvao** [comment]
Heads up that the API is [currently in private beta](https://letterboxd.com/api-coming-soon/).

**Comment by DavCP** [comment]
Is it possible to get the IMDB IDs only instead of opening the browser? I'm just interested in getting this portion of the URL = imdb.com/title/«tt6155172»/

**Comment by tmcknight** [comment]
> Is it possible to get the IMDB IDs only instead of opening the browser? I'm just interested in getting this portion of the URL = imdb.com/title/«tt6155172»/

@DavCP This is done with the latest commit (c247997cb7bac36c21b99cd92418015c5a72f367). Using the copy keyboard shortcut on the IMDb rating item will copy the IMDb ID.

Closing this original issue because it's ancient and Letterboxd API is still in private beta.

**Comment by jun6lee** [comment]
Coming back on this one, would it be possible to add an option where once it's found the film using tmdb id, it could provide a Letterboxd option much like the imdb option, where it opens.. https://letterboxd.com/tmdb/**tmdbid**

API's and grabbing their data aside, this would still be a nice add.

Also, spotted this does exist if it helps: http://api-docs.letterboxd.com/#overview

**Comment by tmcknight** [comment]
Hi @jun6lee - I've added the letterboxd as a result item (30f28951c7435205da8a6756024507aa2fb86381). It's just the URL for now as you've suggested. The API to get the letterboxd rating requires an account and OAuth so while it would be cool, it would increase the complexity of the workflow and I'm not able to tackle this right now. Happy to review pull requests for this functionality though!
