### ISSUE TITLE
Implement search for where to stream

### ISSUE THREAD

**Issue by Donkeyfish87** [tmcknight/Movies-Alfred-Workflow#11]
Perhaps using JustWatch or a similar site, fetch information about where the queried item can be streamed.

**Comment by vitorgalvao** [comment]
> Perhaps using JustWatch

JustWatch doesn’t offer a public API, and from what I see they don’t plan on doing so.

> or a similar site

If you can provide such a website (with an open and well-documented API), we can continue to discuss the feasibility of adding the functionality to the Workflow.

I’m closing the issue, but feel free to comment if you find the website. We can always reopen later.
