### ISSUE TITLE
Rotten Tomatoes has changed the escape character to %xx

### ISSUE THREAD

**Issue by Cocoader** [tmcknight/Movies-Alfred-Workflow#12]
Hi,

 I haven't tested it extensively but Rotten Tomatoes has changed its **escape character** to %xx.

Changing urllib.quote_plus to urllib.quote in **media.py** might have fixed it.

`search = urllib.quote_plus(item[title_key].encode('utf-8'), safe=':'.encode('utf-8'))`

`search = urllib.quote(item[title_key].encode('utf-8'), safe=':'.encode('utf-8'))`

**Comment by tmcknight** [comment]
Hi @Cocoader, Thanks for the bug report and suggested solution!
