### ISSUE TITLE
Would you please add inline metacritic & RT score for TV shows as well (as it works for movies), for TV it only shows imdb score

### ISSUE THREAD

**Issue by frykauf** [tmcknight/Movies-Alfred-Workflow#13]

**Comment by tmcknight** [comment]
@frykauf Hi there. All ratings and info is retrieved from the [OMDb API](http://www.omdbapi.com/). It seems that the RT/Metacritic scores for TV shows aren't as widely available as movies. 

I did a few test searches, and Westworld had an RT score. However, Friends did not. Neither had Metacritic. Whatever the OMDb API has available is what will be shown.

**Comment by frykauf** [comment]
Interesting, thank you for answering this.
