### ISSUE TITLE
Adding Year

### ISSUE THREAD

**Issue by MohammadOtb** [tmcknight/Movies-Alfred-Workflow#15]
Hi,

I would like to add a website with providing title + year on the search. How could I do that?

**Comment by tmcknight** [comment]
Hi @MohammadOtb. There is no official method for adding custom websites to this workflow. However, you can check out the code in media.py under [show_item_info](https://github.com/tmcknight/Movie-and-TV-Show-Search-Alfred-Workflow/blob/2c288ace033b34e8ef82780d4daf50f258542a91/media.py#L108). You'd add something like this:
```python
search_url = 'https://mycoolmoviesite.com/moviesearch?title=' + title
all_search_sites.append(search_url)
wf.add_item(title='Custom Site Name',
              subtitle='Search Custom Site for \'' + item[title_key] + '\'',
              icon='img/imdb.png',
              valid=True,
              arg=search_url)
```
If you tweak that code to the website you wanted and added it around line 158, it should get you what you're after. Good luck!

**Comment by MohammadOtb** [comment]
Yea I added many websites, but I need to specify the year in the search. So no method to extract the year from (get_omdb_info)? I need just the correct command for that (sad face!).

**Comment by tmcknight** [comment]
Try this to get the year:
```python
if item[release_date_key]:
        year = item[release_date_key][:4]
```
