### ISSUE TITLE
Rotten Tomatoes link and one more inline text request

### ISSUE THREAD

**Issue by kenanmike** [tmcknight/Movies-Alfred-Workflow#16]
Thanks *so* much for work on this workflow, it's fantastic! 
Question one: which would improve it even more for me: is it possible to show the Critics Consensus text as well inline, OR if not, then when hitting return/enter after having selected the movie is it possible to open the selected movie's page on RT rather than a search page?
So having selected it in Alfred and hit enter on RT, it would open this page rather than this one.

Question two: I'm not getting any preview of anything when I press shift at any point in the process. I'm on MacOS - any ideas what I need to change?

**Comment by tmcknight** [comment]
Hi @kenanmike,

This workflow uses  [The Open Movie Database](https://omdbapi.com) as its source for RT ratings. Unfortunately, it looks like the breakdown of critic/audience ratings returns "N/A" for movies. It only returns the main tomato meter rating.

As for opening the RT page, It looks like this is doable as the API now returns the RT url. I'll get this implemented soon.

> Question two: I'm not getting any preview of anything when I press shift at any point in the process. I'm on MacOS - any ideas what I need to change?

Check to see that the Quick Look setting is enabled in Alfred (`Alfred Preferences > Features > Previews`). Then, when you search for a movie and hit return to get the details, you should be able to quick look the top item in Alfred. I've noticed that MacOS's quick look has changed the way it renders HTML over the years - and right now, the images aren't displayed. If you hit return on the top item, the page should open and display properly in your browser.
