### ISSUE TITLE
Latest release gives incompatible Python library error

### ISSUE THREAD

**Issue by r3volution11** [tmcknight/Movies-Alfred-Workflow#17]
I just updated to the latest release and Alfred shows that it contains a python library that is incompatible with macOS Sierra 10.12.4+. I'm on Big Sur.

**Comment by tmcknight** [comment]
Sorry about that. The GitHub code had an old, incompatible version of the alfred-workflow library. This was accidentally included in the 2.9 release.

I've released 2.9.1 which should work!
