### ISSUE TITLE
Request: Add an entry to search movie on JustWatch

### ISSUE THREAD

**Issue by reneruiz** [tmcknight/Movies-Alfred-Workflow#18]
This workflow seems excellent! 

Was wondering if you would consider adding an additional entry to search the JustWatch service which can tell you if and where a movie is available for streaming?

**Comment by tmcknight** [comment]
Hi @reneruiz, Good news! I was able to include JustWatch results as the [TMDb API](https://developers.themoviedb.org/3/movies/get-movie-watch-providers) provides them.

A couple things to note:
- The default locale for JustWatch results is set to `US`. If you're in a different country, you can set it in the workflow variables.
- I only included the first provider for each category (stream/buy/rent) in the text of the Alfred result item. To see more, you can select the JustWatch item and it will open the TMDb page that shows all of the providers for your locale. Here's an example:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/468079/136126971-e313dc45-8fdf-4823-bd3b-9b8bc96b8a57.png">

**Comment by reneruiz** [comment]
Amazing response time, thank you!
