### ISSUE TITLE
Broken as of 02-01-17

### ISSUE THREAD

**Issue by mikedvzo** [tmcknight/Movies-Alfred-Workflow#2]
Workflow no longer works and returns the Except Error:  item was not found

**Comment by tmcknight** [comment]
Thanks @mikedvzo. Looks like this is related to [OMDb](https://www.omdbapi.com) being down. I'll keep an eye on it. When the API comes back online (hopefully soon), the workflow will work again.

**Comment by tmcknight** [comment]
The OMDb issues look to be resolved and the workflow is working again.

**Comment by mikedvzo** [comment]
Thanks man I was at a loss with out this workflow
