### ISSUE TITLE
Show region specific rating

### ISSUE THREAD

**Issue by ribrob** [tmcknight/Movies-Alfred-Workflow#21]
Great workflow - love it!

One suggestion / question. Is it possible to configure it to pull the film's certificate for the user's region?

For example, a PG-13 in the US is a 12A in the uk, and you can see that reflected on IMDb.

I've tried changing the `locale` variable to `GB` rather than `US`, but that doesn't do it.

Or am i doing something wrong?

<img width="353" alt="workflow" src="https://user-images.githubusercontent.com/1742832/163597030-6d6e6e1a-55df-43cb-a663-e002df0b25f5.png">

![imdb-us](https://user-images.githubusercontent.com/1742832/163596865-3b6769fe-f7f9-4b11-8e4e-17b4105859ec.jpg)

![imdb-uk](https://user-images.githubusercontent.com/1742832/163596868-25e69eb9-6fbd-4f27-aaa0-d0bdae725b6f.jpg)

**Comment by tmcknight** [comment]
Hi @ribrob, Glad you like the workflow! I've put in some code to grab the proper certification based on the user's locale setting. This'll be included in the next release.
