### ISSUE TITLE
Search stuck after `Queuing argument`

### ISSUE THREAD

**Issue by janmonschke** [tmcknight/Movies-Alfred-Workflow#29]
I noticed that the workflow stopped working for me now. The debugger only shows `Queuing argument 'stranger things'` and nothing happens:

<img width="845" alt="Screenshot 2023-01-11 at 17 42 44" src="https://user-images.githubusercontent.com/68591/211865285-2fc786c6-33de-4e57-b219-12fa94317c97.png">

I installed the workflow via the Alfred gallery, if tha helps.

**Comment by vitorgalvao** [comment]
I cannot reproduce, works well for me with that exact query. What version of macOS are you on?

**Comment by janmonschke** [comment]
@vitorgalvao `MacOS Ventura 13.1`

**Comment by janmonschke** [comment]
Okay, it seemed to have been a temporary issue on my machine. It just started to work again. Will close this issue!
