### ISSUE TITLE
Workflow Error on Movie Search

### ISSUE THREAD

**Issue by r3volution11** [tmcknight/Movies-Alfred-Workflow#3]
This just started happening today for me:

![Screenshot](http://dch.link/flpVervXrb/Screen-Shot-2017-03-07-15-17-20.png)

OMDB appears to be working fine.

**Comment by r3volution11** [comment]
Apparently this was a temporary OMDB issue as the error no longer appears. Apologies!

**Comment by tmcknight** [comment]
@r3volution11 Ahh. Thanks. Glad it's working again.
