### ISSUE TITLE
Can I make it possible to search in a language other than English?

### ISSUE THREAD

**Issue by circumeo** [tmcknight/Movies-Alfred-Workflow#30]
Can I change the settings and make it possible to search in another language?

Thank you in advance 🙏

**Comment by tmcknight** [comment]
Hi @circumeo. I've added a workflow variable to set the search language in the latest version of the workflow.

**Comment by circumeo** [comment]
> Hi @circumeo. I've added a workflow variable to set the search language in the latest version of the workflow.

Thank you so much for the quick correction 😊
However, the results are printed in local language, but the search is still only possible in English
Is this problem possible to solve?
Thank you in advance 🙏
<img width="778" alt="스크린샷 2023-02-14 오후 5 39 24" src="https://user-images.githubusercontent.com/76243664/218683567-b4b8d2fa-349c-48c9-b0cc-433b5d1ca3e6.png">
<img width="778" alt="스크린샷 2023-02-14 오후 5 39 38" src="https://user-images.githubusercontent.com/76243664/218683614-1ca81873-8a42-4fe6-980e-f22755024b1f.png">

**Comment by tmcknight** [comment]
Hi @circumeo. Thanks for trying the new changes. Looks like I may have some more work to do with encoding the search query when calling the backend API.

**Comment by tmcknight** [comment]
Hi @circumeo. This should now be fixed. Just a heads up - the search is using [TheMovieDb](https://www.themoviedb.org) API, so relies on the translations there.

**Comment by circumeo** [comment]
> Hi @circumeo. This should now be fixed. Just a heads up - the search is using [TheMovieDb](https://www.themoviedb.org) API, so relies on the translations there.

Thank you so much for the fix 😊
Thank you for your hard work!
