### ISSUE TITLE
Is there any chance this plugin could show the audience and critic % for movies/tv from Rotten Tomatoes?

### ISSUE THREAD

**Issue by veitch123** [tmcknight/Movies-Alfred-Workflow#33]
Most of the time I use the disparity between what the critics think vs what the audience think as a barometer of the movie. 
Audience loved, critics hated; often not a good movie. 
Audience loathed, critics loved often makes for a movie I'll enjoy. 

I'd love to see the critic and audience percentage. 
Thanks for a great workflow!

**Comment by tmcknight** [comment]
Hi @veitch123. Unfortunately, the API that this workflow uses ([OMDb API](https://www.omdbapi.com)) does not have the rotten tomatoes ratings available. If I'm ever able to get access to the critic/audience scores, I'll definitely add them.
