### ISSUE TITLE
MetaCritic Search String Problem?

### ISSUE THREAD

**Issue by drdannysands** [tmcknight/Movies-Alfred-Workflow#41]
Hi Tom. I love this workflow. But I'm getting bugs with the Metacritic search for TV shows. 

Searching for the TV show "Beef," for example, creates the search string 

`https://www.metacritic.com/search/tv/BEEF/results/`

but this takes me to an error page. If I change the search string to 

`https://www.metacritic.com/search/BEEF/` 

then it performs as expected.

Movie searches seem to work as expected.

Thanks.

**Comment by tmcknight** [comment]
Thanks for the bug report. I've published [v2.19.0](https://github.com/tmcknight/Movie-and-TV-Show-Search-Alfred-Workflow/releases/tag/2.19.0) with the fix.
