### ISSUE TITLE
Internet connection issue (I checked the solutions)

### ISSUE THREAD

**Issue by arturasvlt** [tmcknight/Movies-Alfred-Workflow#47]
Hi. So I have this same thing with 'uh oh, internet connection might be down'. I checked that many people fixed this by using this link https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate/58525755#58525755
which tells to install some kind of certificate. I'm a noob with macbook and maybe you could provide some guidance on how to do this exactly? If I need to use terminal and go to some Python folder - let me know how do I find out my Python version... Thanks in advance

**Comment by tmcknight** [comment]
Hi @arturasvlt, Please read through some of the [latest posts in the workflow forum thread](https://www.alfredforum.com/topic/5355-movie-and-tv-show-search). There may be a solution in there that fixes the issue you're seeing.

If you still can't get it working, I'll need some more info to be able to help. Can you post the workflow [debugger output](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you get the error? Thanks.
