### ISSUE TITLE
OMDb Has Went Private

### ISSUE THREAD

**Issue by r3volution11** [tmcknight/Movies-Alfred-Workflow#5]
OMDb is now private causing the search to die off (no items found). Once you become a Patron (https://www.patreon.com/bePatron?u=5038490) you can get access to the API again for as little as $1 a month.

I modified media.py manually with my key but I was wondernig if you'll be adding support on the front end?

**Comment by r3volution11** [comment]
I just noticed that editing the API link doesn't 100% work. The IMDB URL is stuck on the last movie I searched before OMDb went private I believe.

**Comment by tmcknight** [comment]
Hi @r3volution11 - that sounds like an odd issue... I would try adding the key to the following location on line 103 of media.py:

`params = dict(i=imdb_id, tomatoes=True, apikey='YOURKEYHERE')`

I've not tried this as I'm not interested in paying for an OMDb API key. Good luck!

**Comment by r3volution11** [comment]
That worked. Thank you so much. And since upgrading to High Sierra (I'm a rebel), the browser issue I was having is also gone. 

If someone were to develop the code to add their API key through Alfred, would you grant a pull request? In addition, I was thinking of excluding IMDb ratings unless an API key is provided. Plus adding Trakt support. What do you think?

**Comment by tmcknight** [comment]
I'd certainly grant pull requests!
