### ISSUE TITLE
The item was not found

### ISSUE THREAD

**Issue by inspiredearth** [tmcknight/Movies-Alfred-Workflow#8]
For some time now, I get the error `The item was not found`
The workflow finds the various search results okay, but when selecting the search result (the movie I want info on) it always comes up with that error.

Same issue with TV search.

Any suggestions?

**Comment by vitorgalvao** [comment]
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output.

Also, if you could provide a video, that would work. You can [record your screen with QuickTime Player](https://support.apple.com/en-us/HT201066#record).

**Comment by antonynotna** [comment]
same problem here.
here my debugger output:

Starting debug for 'Movie and TV Show Search'

[2018-04-06 15:04:23][input.scriptfilter] Queuing argument 'lady bird'
[2018-04-06 15:04:24][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:24][STDERR: input.scriptfilter] 15:04:23 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:23 workflow.py:1610 DEBUG    Loading cached data from : /Users/antonysojka/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.mcknight.movies/tmdbconfig.cpickle
15:04:24 workflow.py:1387 DEBUG    Reading settings from `/Users/antonysojka/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:24 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:24 workflow.py:2008 DEBUG    Workflow finished in 0.592 seconds.
[2018-04-06 15:04:24][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item autocomplete="m:391713" valid="no"><title>Lady Bird (2017)</title><subtitle /><arg>391713</arg></item></items>
[2018-04-06 15:04:26][input.scriptfilter] Queuing argument 'm:391713'
[2018-04-06 15:04:27][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:27][STDERR: input.scriptfilter] 15:04:26 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:27 media.py:39 DEBUG    TMDb info retrieved.
15:04:27 workflow.py:1387 DEBUG    Reading settings from `/Users/antonysojka/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:27 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:27 workflow.py:2008 DEBUG    Workflow finished in 1.506 seconds.
[2018-04-06 15:04:27][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>The item was not found.</title><subtitle /></item></items>
[2018-04-06 15:04:35][input.scriptfilter] Queuing argument 'star wars'
[2018-04-06 15:04:41][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:41][STDERR: input.scriptfilter] 15:04:35 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:35 workflow.py:1610 DEBUG    Loading cached data from : /Users/antonysojka/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.mcknight.movies/tmdbconfig.cpickle
15:04:41 workflow.py:1387 DEBUG    Reading settings from `/Users/antonysojka/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:41 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:41 workflow.py:2008 DEBUG    Workflow finished in 5.690 seconds.
[2018-04-06 15:04:41][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item autocomplete="m:11" valid="no"><title>Star Wars (1977)</title><subtitle /><arg>11</arg></item><item autocomplete="m:181808" valid="no"><title>Star Wars: The Last Jedi (2017)</title><subtitle /><arg>181808</arg></item><item autocomplete="m:140607" valid="no"><title>Star Wars: The Force Awakens (2015)</title><subtitle /><arg>140607</arg></item><item autocomplete="m:12180" valid="no"><title>Star Wars: The Clone Wars (2008)</title><subtitle /><arg>12180</arg></item><item autocomplete="m:181812" valid="no"><title>Star Wars: Episode IX (2019)</title><subtitle /><arg>181812</arg></item><item autocomplete="m:330459" valid="no"><title>Rogue One: A Star Wars Story (2016)</title><subtitle /><arg>330459</arg></item><item autocomplete="m:1894" valid="no"><title>Star Wars: Episode II - Attack of the Clones (2002)</title><subtitle /><arg>1894</arg></item><item autocomplete="m:348350" valid="no"><title>Solo: A Star Wars Story (2018)</title><subtitle /><arg>348350</arg></item><item autocomplete="m:1895" valid="no"><title>Star Wars: Episode III - Revenge of the Sith (2005)</title><subtitle /><arg>1895</arg></item><item autocomplete="m:1893" valid="no"><title>Star Wars: Episode I - The Phantom Menace (1999)</title><subtitle /><arg>1893</arg></item><item autocomplete="m:42979" valid="no"><title>Robot Chicken: Star Wars (2007)</title><subtitle /><arg>42979</arg></item><item autocomplete="m:74849" valid="no"><title>The Star Wars Holiday Special (1978)</title><subtitle /><arg>74849</arg></item><item autocomplete="m:333355" valid="no"><title>Star Wars: Clone Wars &#8212; Volume 1 (2005)</title><subtitle /><arg>333355</arg></item><item autocomplete="m:136406" valid="no"><title>Lego Star Wars: The Empire Strikes Out (2012)</title><subtitle /><arg>136406</arg></item><item autocomplete="m:1892" valid="no"><title>Return of the Jedi (1983)</title><subtitle /><arg>1892</arg></item><item autocomplete="m:332479" valid="no"><title>Star Wars: TIE Fighter (2015)</title><subtitle /><arg>332479</arg></item><item autocomplete="m:80829" valid="no"><title>Star Wars: Revelations (2005)</title><subtitle /><arg>80829</arg></item><item autocomplete="m:1891" valid="no"><title>The Empire Strikes Back (1980)</title><subtitle /><arg>1891</arg></item><item autocomplete="m:333365" valid="no"><title>Star Wars: Clone Wars &#8212; Volume 2 (2005)</title><subtitle /><arg>333365</arg></item><item autocomplete="m:70608" valid="no"><title>Lego Star Wars: The Padawan Menace (2011)</title><subtitle /><arg>70608</arg></item></items>
[2018-04-06 15:04:42][input.scriptfilter] Queuing argument 'm:11'
[2018-04-06 15:04:45][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:45][STDERR: input.scriptfilter] 15:04:43 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:45 media.py:39 DEBUG    TMDb info retrieved.
15:04:45 workflow.py:1387 DEBUG    Reading settings from `/Users/antonysojka/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:45 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:45 workflow.py:2008 DEBUG    Workflow finished in 2.674 seconds.
[2018-04-06 15:04:45][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>The item was not found.</title><subtitle /></item></items>

**Comment by antonynotna** [comment]
same problem here.
here my debugger output:

```
Starting debug for 'Movie and TV Show Search'

[2018-04-06 15:04:23][input.scriptfilter] Queuing argument 'lady bird'
[2018-04-06 15:04:24][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:24][STDERR: input.scriptfilter] 15:04:23 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:23 workflow.py:1610 DEBUG    Loading cached data from : /Users/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.mcknight.movies/tmdbconfig.cpickle
15:04:24 workflow.py:1387 DEBUG    Reading settings from `/Users/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:24 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:24 workflow.py:2008 DEBUG    Workflow finished in 0.592 seconds.
[2018-04-06 15:04:24][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item autocomplete="m:391713" valid="no"><title>Lady Bird (2017)</title><subtitle /><arg>391713</arg></item></items>
[2018-04-06 15:04:26][input.scriptfilter] Queuing argument 'm:391713'
[2018-04-06 15:04:27][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:27][STDERR: input.scriptfilter] 15:04:26 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:27 media.py:39 DEBUG    TMDb info retrieved.
15:04:27 workflow.py:1387 DEBUG    Reading settings from `/Users/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:27 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:27 workflow.py:2008 DEBUG    Workflow finished in 1.506 seconds.
[2018-04-06 15:04:27][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>The item was not found.</title><subtitle /></item></items>
[2018-04-06 15:04:35][input.scriptfilter] Queuing argument 'star wars'
[2018-04-06 15:04:41][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:41][STDERR: input.scriptfilter] 15:04:35 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:35 workflow.py:1610 DEBUG    Loading cached data from : /Users/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.mcknight.movies/tmdbconfig.cpickle
15:04:41 workflow.py:1387 DEBUG    Reading settings from `/Users/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:41 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:41 workflow.py:2008 DEBUG    Workflow finished in 5.690 seconds.
[2018-04-06 15:04:41][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item autocomplete="m:11" valid="no"><title>Star Wars (1977)</title><subtitle /><arg>11</arg></item><item autocomplete="m:181808" valid="no"><title>Star Wars: The Last Jedi (2017)</title><subtitle /><arg>181808</arg></item><item autocomplete="m:140607" valid="no"><title>Star Wars: The Force Awakens (2015)</title><subtitle /><arg>140607</arg></item><item autocomplete="m:12180" valid="no"><title>Star Wars: The Clone Wars (2008)</title><subtitle /><arg>12180</arg></item><item autocomplete="m:181812" valid="no"><title>Star Wars: Episode IX (2019)</title><subtitle /><arg>181812</arg></item><item autocomplete="m:330459" valid="no"><title>Rogue One: A Star Wars Story (2016)</title><subtitle /><arg>330459</arg></item><item autocomplete="m:1894" valid="no"><title>Star Wars: Episode II - Attack of the Clones (2002)</title><subtitle /><arg>1894</arg></item><item autocomplete="m:348350" valid="no"><title>Solo: A Star Wars Story (2018)</title><subtitle /><arg>348350</arg></item><item autocomplete="m:1895" valid="no"><title>Star Wars: Episode III - Revenge of the Sith (2005)</title><subtitle /><arg>1895</arg></item><item autocomplete="m:1893" valid="no"><title>Star Wars: Episode I - The Phantom Menace (1999)</title><subtitle /><arg>1893</arg></item><item autocomplete="m:42979" valid="no"><title>Robot Chicken: Star Wars (2007)</title><subtitle /><arg>42979</arg></item><item autocomplete="m:74849" valid="no"><title>The Star Wars Holiday Special (1978)</title><subtitle /><arg>74849</arg></item><item autocomplete="m:333355" valid="no"><title>Star Wars: Clone Wars &#8212; Volume 1 (2005)</title><subtitle /><arg>333355</arg></item><item autocomplete="m:136406" valid="no"><title>Lego Star Wars: The Empire Strikes Out (2012)</title><subtitle /><arg>136406</arg></item><item autocomplete="m:1892" valid="no"><title>Return of the Jedi (1983)</title><subtitle /><arg>1892</arg></item><item autocomplete="m:332479" valid="no"><title>Star Wars: TIE Fighter (2015)</title><subtitle /><arg>332479</arg></item><item autocomplete="m:80829" valid="no"><title>Star Wars: Revelations (2005)</title><subtitle /><arg>80829</arg></item><item autocomplete="m:1891" valid="no"><title>The Empire Strikes Back (1980)</title><subtitle /><arg>1891</arg></item><item autocomplete="m:333365" valid="no"><title>Star Wars: Clone Wars &#8212; Volume 2 (2005)</title><subtitle /><arg>333365</arg></item><item autocomplete="m:70608" valid="no"><title>Lego Star Wars: The Padawan Menace (2011)</title><subtitle /><arg>70608</arg></item></items>
[2018-04-06 15:04:42][input.scriptfilter] Queuing argument 'm:11'
[2018-04-06 15:04:45][input.scriptfilter] Script with argument '(null)' finished
[2018-04-06 15:04:45][STDERR: input.scriptfilter] 15:04:43 workflow.py:1972 DEBUG    Workflow version : 2.3.0
15:04:45 media.py:39 DEBUG    TMDb info retrieved.
15:04:45 workflow.py:1387 DEBUG    Reading settings from `/Users/Library/Application Support/Alfred 3/Workflow Data/com.mcknight.movies/settings.json` ...
15:04:45 workflow.py:2163 DEBUG    Set last run version : 2.3.0
15:04:45 workflow.py:2008 DEBUG    Workflow finished in 2.674 seconds.
[2018-04-06 15:04:45][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>The item was not found.</title><subtitle /></item></items>
```

**Comment by vitorgalvao** [comment]
The reason you’re getting this error is likely that you haven’t set the `omdb_api_key` variable in the Workflow Environment Variables. See [this forum post](https://www.alfredforum.com/topic/5355-movie-and-tv-show-search/?page=3&tab=comments#comment-52477) and after for details.

If that’s not the reason, do let us know and I’ll reopen.
